server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/martinaguerob/config-server
          default-label: "main"
          searchPaths: /
  application:
    name: config-service